### ISSUE TITLE
雅可比矩阵一节的图片配置错误

### ISSUE THREAD

**Issue by RinPV2** [loveunk/machine-learning-deep-learning-notes#2]
![图片](https://github.com/loveunk/machine-learning-deep-learning-notes/assets/38945234/7e9540d3-1d66-4712-b77c-3c24c887ebf8)
[https://github.com/loveunk/machine-learning-deep-learning-notes/blob/master/math/calculus.md#%E4%BE%8B%E5%AD%901](url)

**Comment by loveunk** [comment]
@RinPV2 fixed, thank you for your feedback.
