### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by SeeWhysimon** [loveunk/machine-learning-deep-learning-notes#4]
在你的文档[machine-learning-deep-learning-notes](https://github.com/loveunk/machine-learning-deep-learning-notes/tree/master)当中，提到了利用`df.ix[i, j]`寻找i行j列的元素。但是我在pandas的官方文档中并未找到`ix`这个方法，只找到了具有相似功能的[iloc](https://pandas.pydata.org/docs/user_guide/indexing.html)，是不是您这里不小心打错了呢？

**Comment by bigdata-zhe** [comment]
df.ix[i, j] 是 Pandas 中用于索引 DataFrame 中元素的旧式方法，但在较新的版本中已经被废弃，不推荐使用。

在较新的 Pandas 版本中，推荐使用以下替代方法：

如果要根据行标签和列标签选择元素，则可以使用 .loc[] 属性，如 df.loc[i, j]。
如果要根据行索引和列索引选择元素，则可以使用 .iloc[] 属性，如 df.iloc[i, j]。
这两种方法更清晰、更明确，能够更好地反映您的意图，并且也是 Pandas 官方推荐的用法。
